crate::region! {
    course: FieldLight,
    name: "Lake Hylia",
    color: Name,
    hylia {
        locations: [
            " 10 Maiamai": ItemBowLv2 @None(),
            " 20 Maiamai": ItemBoomerangLv2 @None(),
            " 30 Maiamai": ItemHookshotLv2 @None(),
            " 40 Maiamai": ItemHammerLv2 @None(),
            " 50 Maiamai": ItemBombLv2 @None(),
            " 60 Maiamai": ItemFireRodLv2 @None(),
            " 70 Maiamai": ItemIceRodLv2 @None(),
            " 80 Maiamai": ItemTornadeRodLv2 @None(),
            " 90 Maiamai": ItemSandRodLv2 @None(),
            "100 Maiamai": SpecialMove @None(),
            "Ice Rod Cave": RupeeGold @Chest(CaveLight 9[12]),
            "Lake Hylia Dark Cave": RupeePurple @Chest(CaveLight 11[8]),
            "Lake Hylia Ledge Chest": RupeeR @Chest(35[155]),
            "Lakeside Item Shop (1)": EscapeFruit @None(),
            "Lakeside Item Shop (2)": StopFruit @None(),
            "Lakeside Item Shop (3)": ItemShield @None(),
            "Southeastern Shore": MessageBottle @None(),
            "[Mai] Hyrule Hotfoot Big Rock": Maiamai @Maiamai(36[31]),
            "[Mai] Island Tornado Tile": Maiamai @Maiamai(35[130]),
            "[Mai] Lake Hylia SE Wall": Maiamai @Maiamai(40[24]),
            "[Mai] Lake Hylia Shallow Ring": Maiamai @Maiamai(35[131]),
            "[Mai] Outside Maiamai Cave": Maiamai @Maiamai(35[129]),
        ],
    },
}
