crate::region! {
    course: FieldDark,
    name: "Lorule Castle Area",
    color: Name,
    main {
        locations: [
            "Thieves' Town Crack": None @Crack(16[56] ThievesTown),
            "Vacant House Crack": None @Crack(27[57] VacantHouse),
            "Lorule Right Paradox Crack": None @Crack(32[93] ParadoxRightLorule),
            "Lorule Left Paradox Crack": None @Crack(32[86] ParadoxLeftLorule),
            "Lorule Swamp Pillar Crack": None @Crack(33[216] SwampPillarLorule),

            "Lorule Castle Weather Vane": None @WeatherVane(18[124] LoruleCastleWV),
            "Thieves' Town Weather Vane": None @WeatherVane(16[148] ThievesTownWV),
            "Blacksmith Weather Vane": None @WeatherVane(21[33] BlacksmithWV),
            "Vacant House Weather Vane": None @WeatherVane(27[91] VacantHouseWV),
            "Swamp Palace Weather Vane": None @WeatherVane(33[229] SwampPalaceWV),

            "Big Bomb Flower Cave": RupeeSilver @Chest(CaveDark 2[4]),
            "Blacksmith (Lorule)": ItemSwordLv4 @Event(IndoorDark/FiledDark_22_BlackSmithUra[0x1F]),
            "Pegasus Boots Pyramid": RupeeGold @BigChest(AttractionDark 1[12]),
            "Fortune's Choice": HeartPiece @None(),
            "Great Rupee Fairy": ItemBottle @Event(CaveDark/Cave[0x24]),
            "Lorule Field Hookshot Chest": RupeeSilver @Chest(32[95]),
            "Octoball Derby": HeartPiece @Event(FieldDark_2A_GameMaster[0x21]),
            "Rupee Rush (Lorule)": HeartPiece @Event(FieldDark_28_Minigame[0x26]),
            "Swamp Cave (Left)": RupeeSilver @Chest(CaveDark 3[3]),
            "Swamp Cave (Middle)": HeartPiece @Heart(CaveDark 3[8]),
            "Swamp Cave (Right)": RupeeGold @Chest(CaveDark 3[6]),
            "Thief Girl": RupeeSilver @Chest(CaveDark 15[9]),
            "Thieves' Town Item Shop (1)": Bee @None(),
            "Thieves' Town Item Shop (2)": GoldenBeeForSale @None(),
            "Thieves' Town Item Shop (3)": Fairy @None(),
            "Thieves' Town Item Shop (4)": Shield @None(),
            "Vacant House": ItemBottle @Chest(IndoorDark 11[31]),
            "[Mai] Behind Vacant House": Maiamai @Maiamai(27[88]),
            "[Mai] Big Bomb Flower Grass": Maiamai @Maiamai(24[88]),
            "[Mai] Lorule Blacksmith Wall": Maiamai @Maiamai(21[24]),
            "[Mai] Lorule Castle Tree": Maiamai @Maiamai(18[73]),
            "[Mai] Lorule Castle Wall": Maiamai @Maiamai(18[74]),
            "[Mai] Lorule Fortune-Teller Rock": Maiamai @Maiamai(17[69]),
            "[Mai] Lorule Haunted Grove Wall": Maiamai @Maiamai(32[99]),
            "[Mai] Lorule Rupee Rush Wall": Maiamai @Maiamai(39[568]),
            "[Mai] Lorule S Ruins Pillars": Maiamai @Maiamai(33[253]),
            "[Mai] Lorule S Ruins Wall": Maiamai @Maiamai(33[226]),
            "[Mai] Lorule S Ruins Water": Maiamai @Maiamai(33[227]),
            "[Mai] Octoball Derby Skull": Maiamai @Maiamai(25[17]),
            "[Mai] Thieves' Town Tree": Maiamai @Maiamai(16[108]),
            "[Mai] Thieves' Town Wall": Maiamai @Maiamai(16[107]),
            "[Mai] Vacant House Rock": Maiamai @Maiamai(26[42]),
        ],
    },
}
