crate::region! {
    course: FieldDark,
    name: "Lorule Castle Area",
    color: Name,
    main {
        locations: [
            "Swamp Palace Entrance": None @Door(33[158] SwampPalaceEntrance),
            "Thieves' Hideout Entrance": None @Door(16[54] ThievesHideoutEntrance),
            "Lorule Castle Entrance": None @Door(18[34] LoruleCastleEntrance),
            "Vacant House Front Entrance": None @Door (27[16] VacantHouseFrontEntrance),
            "Vacant House Front Exit": None @Door (IndoorDark 11[27] VacantHouseFrontExit),
            "Vacant House Back Entrance": None @Door (27[85] VacantHouseBackEntrance),
            "Vacant House Back Exit": None @Door (IndoorDark 11[33] VacantHouseBackExit),
            "Thief Girl Cave Entrance": None @Door (33[258] ThiefGirlCaveEntrance),
            "Thief Girl Cave Exit": None @Door (CaveDark 15[7] ThiefGirlCaveExit),
            "Swamp Cave Entrance": None @Door (33[204] SwampCaveEntrance),
            "Swamp Cave Exit": None @Door (CaveDark 3[7] SwampCaveExit),
            "Bomb Flower Cave Entrance": None @Door (32[91] BombFlowerCaveEntrance),
            "Bomb Flower Cave Exit": None @Door (CaveDark 2[7] BombFlowerCaveExit),
            "Great Rupee Fairy Cave Entrance": None @Door (24[90] GreatRupeeFairyCaveEntrance),
            "Great Rupee Fairy Cave Exit": None @Door (CaveDark 14[3] GreatRupeeFairyCaveExit),
            "Bomb Flower Shop Entrance": None @Door (24[45] BombFlowerShopEntrance),
            "Bomb Flower Shop Exit": None @Door (IndoorDark 3[32] BombFlowerShopExit),
            "Lorule Blacksmith Entrance": None @Door (21[8] LoruleBlacksmithEntrance),
            "Lorule Blacksmith Exit": None @Door (IndoorDark 4[4] LoruleBlacksmithExit),
            "Lorule Fortune-Teller Entrance": None @Door (17[82] LoruleFortuneTellerEntrance),
            "Lorule Fortune-Teller Exit": None @Door (IndoorDark 10[1] LoruleFortuneTellerExit),
            "Lorule Milk Bar Entrance": None @Door (16[141] LoruleMilkBarEntrance),
            "Lorule Milk Bar Exit": None @Door (IndoorDark 1[0] LoruleMilkBarExit),
            "Veteran Thief's House Entrance": None @Door (16[130] VeteransHouseEntrance),
            "Veteran Thief's House Exit": None @Door (IndoorDark 16[5] VeteransHouseExit),
            "Lorule Fortune's Choice Entrance": None @Door (16[121] LoruleFortunesChoiceEntrance),
            "Lorule Fortune's Choice Exit": None @Door (IndoorDark 14[5] LoruleFortunesChoiceExit),
            "Thieves' Town Item Shop Entrance": None @Door (16[111] ThievesTownItemShopEntrance),
            "Thieves' Town Item Shop Exit": None @Door (IndoorDark 13[12] ThievesTownItemShopExit),

            "Thieves' Town Crack": None @Crack(16[56] ThievesTown),
            "Vacant House Crack": None @Crack(27[57] VacantHouse),
            "Lorule Right Paradox Crack": None @Crack(32[93] ParadoxRightLorule),
            "Lorule Left Paradox Crack": None @Crack(32[86] ParadoxLeftLorule),
            "Lorule Swamp Pillar Crack": None @Crack(33[216] SwampPillarLorule),

            "Lorule Castle Weather Vane": None @WeatherVane(18[124] LoruleCastleWV),
            "Thieves' Town Weather Vane": None @WeatherVane(16[148] ThievesTownWV),
            "Blacksmith Weather Vane": None @WeatherVane(21[33] BlacksmithWV),
            "Vacant House Weather Vane": None @WeatherVane(27[91] VacantHouseWV),
            "Swamp Palace Weather Vane": None @WeatherVane(33[229] SwampPalaceWV),

            "Big Bomb Flower Cave": RupeeSilver @Chest(CaveDark 2[4]),
            "Blacksmith (Lorule)": ItemSwordLv4 @Event(IndoorDark/FiledDark_22_BlackSmithUra[0x1F]),
            "Pegasus Boots Pyramid": RupeeGold @BigChest(AttractionDark 1[12]),
            "Fortune's Choice": HeartPiece @None(),
            "Great Rupee Fairy": ItemBottle @Event(CaveDark/Cave[0x24]),
            "Lorule Field Hookshot Chest": RupeeSilver @Chest(32[95]),
            "Octoball Derby": HeartPiece @Event(FieldDark_2A_GameMaster[0x21]),
            "Rupee Rush (Lorule)": HeartPiece @Event(FieldDark_28_Minigame[0x26]),
            "Swamp Cave (Left)": RupeeSilver @Chest(CaveDark 3[3]),
            "Swamp Cave (Middle)": HeartPiece @Heart(CaveDark 3[8]),
            "Swamp Cave (Right)": RupeeGold @Chest(CaveDark 3[6]),
            "Thief Girl": RupeeSilver @Chest(CaveDark 15[9]),
            "Thieves' Town Item Shop (1)": Bee @None(),
            "Thieves' Town Item Shop (2)": GoldenBeeForSale @None(),
            "Thieves' Town Item Shop (3)": Fairy @None(),
            "Thieves' Town Item Shop (4)": Shield @None(),
            "Vacant House": ItemBottle @Chest(IndoorDark 11[31]),
            "[Mai] Behind Vacant House": Maiamai @Maiamai(27[88]),
            "[Mai] Big Bomb Flower Grass": Maiamai @Maiamai(24[88]),
            "[Mai] Lorule Blacksmith Wall": Maiamai @Maiamai(21[24]),
            "[Mai] Lorule Castle Tree": Maiamai @Maiamai(18[73]),
            "[Mai] Lorule Castle Wall": Maiamai @Maiamai(18[74]),
            "[Mai] Lorule Fortune-Teller Rock": Maiamai @Maiamai(17[69]),
            "[Mai] Lorule Haunted Grove Wall": Maiamai @Maiamai(32[99]),
            "[Mai] Lorule Rupee Rush Wall": Maiamai @Maiamai(39[568]),
            "[Mai] Lorule S Ruins Pillars": Maiamai @Maiamai(33[253]),
            "[Mai] Lorule S Ruins Wall": Maiamai @Maiamai(33[226]),
            "[Mai] Lorule S Ruins Water": Maiamai @Maiamai(33[227]),
            "[Mai] Octoball Derby Skull": Maiamai @Maiamai(25[17]),
            "[Mai] Thieves' Town Tree": Maiamai @Maiamai(16[108]),
            "[Mai] Thieves' Town Wall": Maiamai @Maiamai(16[107]),
            "[Mai] Vacant House Rock": Maiamai @Maiamai(26[42]),
        ],
    },
}
