crate::region! {
    course: FieldLight,
    name: "Death Mountain",
    color: Name,
    mountain {
        locations: [
            "Tower of Hera Entrance": None @Door(3[14] TowerOfHeraEntrance),
            "Moldorm Cave Top Entrance": None @Door (3[12] MoldormCaveTopEntrance),
            "Moldorm Cave Top Exit": None @Door (CaveLight 19[5] MoldormCaveTopExit),
            "Death Mountain Bomb Cave Entrance": None @Door (3[184] DeathMountainBombCaveEntrance),
            "Death Mountain Bomb Cave Exit": None @Door (CaveLight 3[51] DeathMountainBombCaveExit),
            "Death Mountain Weather Vane Left Cave Entrance": None @Door (3[183] DeathMountainWeatherVaneLeftCaveEntrance),
            "Death Mountain Weather Vane Left Cave Exit": None @Door (CaveLight 3[50] DeathMountainWeatherVaneLeftCaveExit),
            "Death Mountain Fairy Cave Entrance": None @Door (3[188] DeathMountainWestFairyCaveEntrance),
            "Death Mountain Fairy Cave Exit": None @Door (CaveLight 3[53] DeathMountainWestFairyCaveExit),
            "Donkey Cave Lower Entrance": None @Door (3[82] DonkeyCaveLowerEntrance),
            "Donkey Cave Lower Exit": None @Door (CaveLight 1[64] DonkeyCaveLowerExit),
            "Donkey Cave Middle Entrance": None @Door (3[84] DonkeyCaveMiddleEntrance),
            "Donkey Cave Middle Exit": None @Door (CaveLight 1[63] DonkeyCaveMiddleExit),
            "Donkey Cave Upper Entrance": None @Door (3[83] DonkeyCaveUpperEntrance),
            "Donkey Cave Upper Exit": None @Door (CaveLight 1[62] DonkeyCaveUpperExit),
            "Big Rolling Rocks Cave Lower Entrance": None @Door (3[94] BigRollingRocksCaveLowerEntrance),
            "Big Rolling Rocks Cave Lower Exit": None @Door (CaveLight 2[50] BigRollingRocksCaveLowerExit),
            "Big Rolling Rocks Cave Middle Right Entrance": None @Door (3[193] BigRollingRocksCaveMiddleRightEntrance),
            "Big Rolling Rocks Cave Middle Right Exit": None @Door (CaveLight 2[99] BigRollingRocksCaveMiddleRightExit),
            "Big Rolling Rocks Cave Middle Left Entrance": None @Door (3[190] BigRollingRocksCaveMiddleLeftEntrance),
            "Big Rolling Rocks Cave Middle Left Exit": None @Door (CaveLight 2[66] BigRollingRocksCaveMiddleLeftExit),
            "Big Rolling Rocks Cave Upper Entrance": None @Door (3[195] BigRollingRocksCaveUpperEntrance),
            "Big Rolling Rocks Cave Upper Exit": None @Door (CaveLight 2[70] BigRollingRocksCaveUpperExit),
            "Spectacle Rock Cave Left Entrance": None @Door (3[305] SpectacleRockCaveLeftEntrance),
            "Spectacle Rock Cave Left Exit": None @Door (CaveLight 3[87] SpectacleRockCaveLeftExit),
            "Spectacle Rock Cave Right Entrance": None @Door (3[307] SpectacleRockCaveRightEntrance),
            "Spectacle Rock Cave Right Exit": None @Door (CaveLight 3[85] SpectacleRockCaveRightExit),
            "Hookshot Mini Dungeon Entrance": None @Door (5[48] HookshotMiniDungeonEntrance),
            "Hookshot Mini Dungeon Exit": None @Door (AttractionLight 4[3] HookshotMiniDungeonExit),
            "Fire Cave Top Entrance": None @Door (4[51] FireCaveTopEntrance),
            "Fire Cave Top Exit": None @Door (CaveLight 25[105] FireCaveTopExit),
            "Fire Cave Middle Left Entrance": None @Door (4[52] FireCaveMiddleLeftEntrance),
            "Fire Cave Middle Left Exit": None @Door (CaveLight 25[106] FireCaveMiddleLeftExit),
            "Fire Cave Middle Right Entrance": None @Door (4[53] FireCaveMiddleRightEntrance),
            "Fire Cave Middle Right Exit": None @Door (CaveLight 25[107] FireCaveMiddleRightExit),
            "Fire Cave Bottom Entrance": None @Door (4[54] FireCaveBottomEntrance),
            "Fire Cave Bottom Exit": None @Door (CaveLight 25[108] FireCaveBottomExit),
            "Death Mountain Big Fairy Cave Entrance": None @Door (4[56] DeathMountainBigFairyCaveEntrance),
            "Death Mountain Big Fairy Cave Exit": None @Door (CaveLight 24[5] DeathMountainBigFairyCaveExit),

            "Hyrule Death West Crack": None @Crack(3[361] DeathWestHyrule),
            "Hyrule Floating Island Crack": None @Crack(4[111] FloatingIslandHyrule),
            "Hyrule Rosso's Ore Mine Crack": None @Crack(4[65] RossosOreMineHyrule),

            "Death Mountain (Hyrule) Weather Vane": None @WeatherVane(3[349] DeathMountainHyruleWV),
            "Tower of Hera Weather Vane": None @WeatherVane(3[335] TowerOfHeraWV),

            "Bouldering Guy": ItemBottle @Event(FieldLight_05_Climber[0x06]),
            "Death Mountain Open Cave": RupeeB @Chest(CaveLight 3[58]),
            "Death Mountain Blocked Cave": RupeePurple @Chest(CaveLight 3[59]),
            "Death Mountain Fairy Cave": LiverPurple @Chest(CaveLight 3[83]),
            "Death Mountain West Highest Cave": LiverPurple @Chest(CaveLight 2[166]),
            "Donkey Cave": LiverPurple @Chest(CaveLight 1[67]),
            "Donkey Cave Ledge": RupeeR @Chest(3[303]),
            "Fire Cave Pillar": HeartPiece @Heart(CaveLight 25[9]),
            "Floating Island": HeartPiece @Heart(4[25]),
            "Hookshot Mini-Dungeon": RupeeSilver @Chest(AttractionLight 4[89]),
            "Spectacle Rock": HeartPiece @Heart(3[302]),
            "[Mai] Death Mountain Base Rock": Maiamai @Maiamai(3[357]),
            "[Mai] Fire Cave Ledge": Maiamai @Maiamai(4[63]),
            "[Mai] Death Mountain West Ledge": Maiamai @Maiamai(3[358]),
            "[Mai] Outside Hookshot Mini-Dungeon": Maiamai @Maiamai(5[23]),
            "[Mai] Rosso's Ore Mine": Maiamai @Maiamai(4[64]),
        ],
    },
}
