crate::region! {
    course: FieldLight,
    name: "Eastern Ruins",
    color: Name,
    ruins {
        locations: [
            "Eastern Palace Entrance": None @Door(20[36] EasternPalaceEntrance),
            "Merge Mini Dungeon Entrance": None @Door (20[164] MergeMiniDungeonEntrance),
            "Merge Mini Dungeon Exit": None @Door (AttractionLight 1[3] MergeMiniDungeonExit),
            "Eastern Ruins Fairy Cave Entrance": None @Door (30[71] EasternRuinsFairyCaveEntrance),
            "Eastern Ruins Fairy Cave Exit": None @Door (CaveLight 10[5] EasternRuinsFairyCaveExit),
            "Eastern Ruins Big Fairy Cave Entrance": None @Door (29[49] EasternRuinsBigFairyCaveEntrance),
            "Eastern Ruins Big Fairy Cave Exit": None @Door (CaveLight 12[5] EasternRuinsBigFairyCaveExit),
            "Eastern Ruins Cave Top Entrance": None @Door (20[160] EasternRuinsCaveTopEntrance),
            "Eastern Ruins Cave Top Exit": None @Door (CaveLight 29[4] EasternRuinsCaveTopExit),
            "Eastern Ruins Cave Bottom Entrance": None @Door (20[161] EasternRuinsCaveBottomEntrance),
            "Eastern Ruins Cave Bottom Exit": None @Door (CaveLight 29[3] EasternRuinsCaveBottomExit),
            "Witch Cave Front Entrance": None @Door (20[162] WitchCaveFrontEntrance),
            "Witch Cave Front Exit": None @Door (CaveLight 30[3] WitchCaveFrontExit),

            "Eastern Ruins Pillar Crack": None @Crack(22[33] EasternRuinsPillar),
            "Eastern Ruins SE Crack": None @Crack(30[54] EasternRuinsSE),
            "Hyrule River Crack": None @Crack(29[46] RiverHyrule),

            "Eastern Palace Weather Vane": None @WeatherVane(20[57] EasternPalaceWV),

            "Bird Lover": ItemBottle @Event(FieldLight_2D_UnderBridgeStranger[0x2A]),
            "Eastern Ruins Armos Chest": RupeeR @Chest(20[106]),
            "Eastern Ruins Cave": HeartPiece @Heart(CaveLight 29[10]),
            "Eastern Ruins Hookshot Chest": RupeeR @Chest(20[111]),
            "Eastern Ruins Merge Chest": RupeeSilver @Chest(20[107]),
            "Eastern Ruins Peg Circle": HeartPiece @Heart(30[41]),
            "Merge Mini-Dungeon": RupeeSilver @Chest(AttractionLight 1[4]),
            "[Mai] Eastern Ruins Bonk Rocks": Maiamai @Maiamai(22[42]),
            "[Mai] Eastern Ruins Rock": Maiamai @Maiamai(30[69]),
            "[Mai] Eastern Ruins Green Tree": Maiamai @Maiamai(29[44]),
            "[Mai] Eastern Ruins River": Maiamai @Maiamai(28[45]),
            "[Mai] Eastern Ruins Wall": Maiamai @Maiamai(20[144]),
            "[Mai] Eastern Ruins Yellow Tree": Maiamai @Maiamai(20[145]),
        ],
    },
}
