crate::region! {
    course: FieldLight,
    name: "Hyrule Castle Area",
    color: Name,
    main {
        locations: [
            "Inside Hyrule Castle Entrance": None @Door(18[155] InsideHyruleCastleEntrance),

            "Blacksmith Entrance": None @Door(21[79] BlacksmithEntrance),
            "Blacksmith Exit": None @Door(IndoorLight 19[2] BlacksmithExit),
            "Blacksmith Cave Entrance": None @Door(21[150] BlacksmithCaveEntrance),
            "Blacksmith Cave Exit": None @Door(CaveLight 16[4] BlacksmithCaveExit),
            "Cucco Mini Dungeon Entrance": None @Door(32[62] CuccoMiniDungeonEntrance),
            "Cucco Mini Dungeon Exit": None @Door(AttractionLight 3[12] CuccoMiniDungeonExit),
            "Hyrule Castle Upper Left Entrance": None @Door(18[159] HyruleCastleUpperLeftEntrance),
            "Hyrule Castle Upper Left Exit": None @Door(IndoorLight 12[19] HyruleCastleUpperLeftExit),
            "Hyrule Castle Upper Right Entrance": None @Door(18[154] HyruleCastleUpperRightEntrance),
            "Hyrule Castle Upper Right Exit": None @Door(IndoorLight 12[18] HyruleCastleUpperRightExit),
            "Hyrule Castle Lower Left Entrance": None @Door(18[374] HyruleCastleLowerLeftEntrance),
            "Hyrule Castle Lower Left Exit": None @Door(IndoorLight 12[50] HyruleCastleLowerLeftExit),
            "Hyrule Castle Lower Right Entrance": None @Door(18[375] HyruleCastleLowerRightEntrance),
            "Hyrule Castle Lower Right Exit": None @Door(IndoorLight 12[51] HyruleCastleLowerRightExit),
            "Hyrule Castle Main Entrance": None @Door(18[160] HyruleCastleMainEntrance),
            "Hyrule Castle Main Exit": None @Door(IndoorLight 12[17] HyruleCastleMainExit),

            "Your House Crack": None @Crack(27[68] YourHouse),
            "Hyrule Right Paradox Crack": None @Crack(32[60] ParadoxRightHyrule),
            "Hyrule Left Paradox Crack": None @Crack(32[56] ParadoxLeftHyrule),

            "Your House Weather Vane": None @WeatherVane(27[48] YourHouseWV),

            "Blacksmith": ItemSwordLv3 @Event(IndoorLight/FieldLight_22_BlackSmith[0x16]),
            "Blacksmith Cave": HeartPiece @Heart(CaveLight 16[1]),
            "Blacksmith Ledge": HeartPiece @Heart(17[95]),
            "Blacksmith Table": PackageSword @Chest(IndoorLight 19[12]),
            "Cucco Mini-Dungeon": RupeeSilver @SilverRupee(AttractionLight 3[9]),
            "Haunted Grove Stump": Pouch @Event(FieldLight_2A_BlacksmithWife[0x15]),
            "Hyrule Castle Rocks": HeartPiece @Heart(18[209]),
            "[Mai] Behind Your House": Maiamai @Maiamai(27[112]),
            "[Mai] Blacksmith Tiles": Maiamai @Maiamai(21[122]),
            "[Mai] Blacksmith Tree": Maiamai @Maiamai(17[73]),
            "[Mai] Outside Cucco Mini-Dungeon": Maiamai @Maiamai(32[59]),
            "[Mai] Haunted Grove Tree": Maiamai @Maiamai(25[118]),
            "[Mai] Hyrule Castle Tiles": Maiamai @Maiamai(18[307]),
            "[Mai] Hyrule Castle Tree": Maiamai @Maiamai(18[305]),
            "[Mai] Your House Tree": Maiamai @Maiamai(26[49]),
        ],
    },
}
