crate::region! {
    course: FieldLight,
    name: "Hyrule Field",
    main {
        locations: [
            "Blacksmith Table": PackageSword @Chest(IndoorLight 19[12]),
            "Dampe": ItemSwordLv1 @Event(FieldLight_13_Sister[0x1D]),
            "Rosso Cave": RupeeR @Chest(CaveLight 6[6]) :- {|p| p.can_hammer() || (p.glitched() && (p.can_boomerang() || p.can_hookshot()))},
            "Sanctuary Pegs": RupeeSilver @Chest(11[89]) :- can_hammer,
            "Sanctuary Treasure Dungeon": RupeeSilver @Chest(AttractionLight 5[24]) :- {|p| p.can_bomb() && p.can_merge()},
            "Behind Blacksmith": HeartPiece @Heart(17[95]) :- {|p| p.can_merge() || (p.glitched() && p.can_ledge_boost())},
            "Blacksmith Cave": HeartPiece @Heart(CaveLight 16[1]) :- {|p| p.can_lift_big() || (p.glitched() && p.can_ledge_boost())},
            "Blacksmith": ItemSwordLv3 @Event(IndoorLight/FieldLight_22_BlackSmith[0x16]) :- {|p| p.can_merge() && p.ore() >= 2},
            "Castle Rocks": HeartPiece @Heart(18[209]) :- can_lift,
            "Rosso": PowerGlove @Chest(IndoorLight 10[7]) :- {|p| p.did_eastern() || p.can_merge()},
            "Cucco Dungeon": RupeeSilver @SilverRupee(AttractionLight 3[9]),
            // "Thanks": RingHekiga @Event(IndoorLight/FieldLight_2C_Rental[0xED]),
            "Clean Rocks": RupeePurple @Chest(IndoorLight 10[25]) :- can_lift,
            "Irene": ItemBell @Event[
                FieldLight_11_Maple[0x06],
                FieldLight_12_Maple[0x08],
                FieldLight_12_Maple[0x26],
                FieldLight_2D_Maple[0x07],
            ],
            "Wildlife Clearing Stump": ItemRentalTornadeRod @Event(FieldLight_2A_BlacksmithWife[0x15]),
            "Ravio (1)": ItemRentalIceRod @Shop(Ravio(0)),
            "Ravio (2)": DashBoots @Shop(Ravio(5)),
            "Ravio (3)": Pouch @Shop(Ravio(2)),
            "Ravio (4)": ItemBell @Shop(Ravio(3)),
            "Ravio (5)": RingHekiga @Shop(Ravio(8)),
            "Ravio (6)": ItemRentalSandRod @Shop(Ravio(1)) :- osfala,
            "Ravio (7)": ItemRentalHammer @Shop(Ravio(7)),
            "Ravio (8)": ItemRentalBoomerang @Shop(Ravio(6)),
            "Ravio (9)": ItemRentalFireRod @Shop(Ravio(4)),
            "Rupee Rush (Hyrule)": HeartPiece @Event(FieldLight_28_Minigame[0x26]),
            "Sanctuary Cave": HeartPiece @Heart(CaveLight 5[2]),
        ],
    },
}
