crate::region! {
    course: FieldLight,
    name: "Central Hyrule",
    color: Name,
    main {
        locations: [
            "Cucco Treasure Dungeon": RupeeSilver @SilverRupee(AttractionLight 3[9]),
            "Blacksmith": ItemSwordLv3 @Event(IndoorLight/FieldLight_22_BlackSmith[0x16]),
            "Blacksmith Table": PackageSword @Chest(IndoorLight 19[12]),
            "Behind Blacksmith": HeartPiece @Heart(17[95]),
            "Blacksmith Cave": HeartPiece @Heart(CaveLight 16[1]),
            "Hyrule Castle Rocks": HeartPiece @Heart(18[209]),
            "Ravio (1)": ItemRentalIceRod @Shop(Ravio(0)),
            "Ravio (2)": ItemRentalHookshot @Shop(Ravio(5)),
            "Ravio (3)": ItemRentalTornadeRod @Shop(Ravio(2)),
            "Ravio (4)": ItemRentalBomb @Shop(Ravio(3)),
            "Ravio (5)": ItemRentalBow @Shop(Ravio(8)),
            "Ravio (6)": ItemRentalSandRod @Shop(Ravio(1)),
            "Ravio (7)": ItemRentalHammer @Shop(Ravio(7)),
            "Ravio (8)": ItemRentalBoomerang @Shop(Ravio(6)),
            "Ravio (9)": ItemRentalFireRod @Shop(Ravio(4)),
            // "Thanks": RingHekiga @Event(IndoorLight/FieldLight_2C_Rental[0xED]),
            "Wildlife Clearing Stump": Pouch @Event(FieldLight_2A_BlacksmithWife[0x15]),
            "[Mai] Cucco Dungeon Big Rock": Maiamai @Maiamai(32[59]),
            "[Mai] Behind Link's House": Maiamai @Maiamai(27[112]),
            "[Mai] Blacksmith Tornado Tile": Maiamai @Maiamai(21[122]),
            "[Mai] Hyrule Castle Tornado Tile": Maiamai @Maiamai(18[307]),
            "[Mai] Hyrule Castle Tree": Maiamai @Maiamai(18[305]),
            "[Mai] Tree Behind Blacksmith": Maiamai @Maiamai(17[73]),
            "[Mai] Tree West of Link's House": Maiamai @Maiamai(26[49]),
            "[Mai] Wildlife Clearing Tree": Maiamai @Maiamai(25[118]),
        ],
    },
}
