crate::region! {
    course: FieldLight,
    name: "Kakariko Village",
    color: Name,
    village {
        locations: [
            "Milk Bar Entrance": None @Door(16[271] MilkBarEntrance),
            "Milk Bar Exit": None @Door(IndoorLight 15[5] MilkBarExit),
            "Cucco House Front Entrance": None @Door(16[403] CuccoHouseFrontEntrance),
            "Cucco House Front Exit": None @Door(IndoorLight 9[4] CuccoHouseFrontExit),
            "Cucco House Back Entrance": None @Door(16[404] CuccoHouseBackEntrance),
            "Cucco House Back Exit": None @Door(IndoorLight 9[5] CuccoHouseBackExit),
            "Stylish Woman's House Entrance": None @Door([16[206],16[272],] StylishWomansHouseEntrance),
            "Stylish Woman's House Exit": None @Door(IndoorLight 14[5] StylishWomansHouseExit),
            "Bee Guy's House Entrance": None @Door(16[208] BeeGuyHouseEntrance),
            "Bee Guy's House Exit": None @Door(IndoorLight 17[5] BeeGuyHouseExit),
            "Hyrule Fortune's Choice Entrance": None @Door(16[283] HyruleFortunesChoiceEntrance),
            "Hyrule Fortune's Choice Exit": None @Door(IndoorLight 20[5] HyruleFortunesChoiceExit),
            "Woman's House Entrance": None @Door(16[284] WomanHouseEntrance),
            "Woman's House Exit": None @Door(IndoorLight 21[5] WomanHouseExit),
            "Kakariko Item Shop Entrance": None @Door(16[269] KakarikoItemShopEntrance),
            "Kakariko Item Shop Exit": None @Door(IndoorLight 8[5] KakarikoItemShopExit),
            "Jail Entrance": None @Door(16[396] JailEntrance),
            "Jail Exit": None @Door(IndoorLight 3[4] JailExit),
            "Sahasrahla's House Left Entrance": None @Door(16[262] SahasrahlaLeftEntrance),
            "Sahasrahla's House Left Exit": None @Door(IndoorLight 16[11] SahasrahlaLeftExit),
            "Sahasrahla's House Right Entrance": None @Door(16[258] SahasrahlaRightEntrance),
            "Sahasrahla's House Right Exit": None @Door(IndoorLight 16[4] SahasrahlaRightExit),
            "Kakariko Cave Entrance": None @Door(16[278] KakarikoCaveEntrance),
            "Kakariko Cave Exit": None @Door(CaveLight 4[7] KakarikoCaveExit),

            "Stylish Woman's House Crack": None @Crack(IndoorLight 14[7] StylishWoman),
            "Sahasrahla's House Crack": None @Crack(16[275] SahasrahlasHouse),

            "Kakariko Village Weather Vane": None @WeatherVane(16[203] KakarikoVillageWV),

            "Bee Guy (1)": ItemInsectNet @Event(IndoorLight/FieldLight_18_InsectNet[0xB]),
            "Bee Guy (2)": BadgeBee @Event(IndoorLight/FieldLight_18_InsectNet[0x1F]),
            "Dodge the Cuccos": HeartPiece @Event(FieldLight_29_Kokko[0x67]),
            "Kakariko Item Shop (Left)": EscapeFruit @None(),
            // "Kakariko Item Shop (Center)": StopFruit @None(),
            "Kakariko Item Shop (Right)": ItemShield @None(),
            "Kakariko Jail": RupeeSilver @Chest(IndoorLight 3[3]),
            "Kakariko Well (Bottom)": RupeeR @Chest(CaveLight 4[6]),
            "Kakariko Well (Top)": HeartPiece @Heart(CaveLight 4[8]),
            "Rupee Rush (Hyrule)": HeartPiece @Event(FieldLight_28_Minigame[0x26]),
            "Shady Guy": ItemRentalHookShot @Event(FieldLight_18_Touzoku[0x12]),
            "Street Merchant (Left)": ItemBottle @Shop(Merchant(0)),
            "Street Merchant (Right)": ItemStoneBeauty @Shop(Merchant(2)),
            "Stylish Woman": HeartPiece @Event(IndoorLight/FieldLight_18_ClosedHouse[4]),
            "Stylish Woman (Repeat)": Heart @Event(IndoorLight/FieldLight_18_ClosedHouse[24]),
            "Woman": RupeeR @Event(IndoorLight/FieldLight_18_MiddleLady[0xF]),
            "[Mai] Cucco Ranch Tree": Maiamai @Maiamai(24[42]),
            "[Mai] Hyrule Rupee Rush Wall": Maiamai @Maiamai(45[46]),
            "[Mai] Kakariko Bush": Maiamai @Maiamai(16[304]),
            "[Mai] Kakariko Sand": Maiamai @Maiamai(16[393]),
            "[Mai] Woman's Roof": Maiamai @Maiamai(16[394]),
        ],
    },
}
