crate::region! {
    course: FieldLight,
    name: "Lost Woods Area",
    color: Name,
    woods {
        locations: [
            "Fortune-Teller Tent Entrance": None @Door (9[68] FortuneTellerTentEntrance),
            "Fortune-Teller Tent Exit": None @Door (IndoorLight 18[5] FortuneTellerTentExit),
            "Fortune-Teller Cave Entrance": None @Door (9[92] FortuneTellerCaveEntrance),
            "Fortune-Teller Cave Exit": None @Door (CaveLight 21[3] FortuneTellerCaveExit),
            "Rumor Guy Cave Entrance": None @Door (1[233] RumorGuyCaveEntrance),
            "Rumor Guy Cave Exit": None @Door (CaveLight 17[3] RumorGuyCaveExit),
            "Rosso's House Entrance": None @Door (2[136] RossoHouseEntrance),
            "Rosso's House Exit": None @Door (IndoorLight 10[5] RossoHouseExit),
            "Rosso Cave Entrance": None @Door (2[95] RossoCaveEntrance),
            "Rosso Cave Exit": None @Door (CaveLight 6[7] RossoCaveExit),
            "Moldorm Cave Lower Entrance": None @Door (6[10] MoldormCaveLowerEntrance),
            "Moldorm Cave Lower Exit": None @Door (CaveLight 19[4] MoldormCaveLowerExit),
            "Moldorm Cave Ledge Entrance": None @Door (6[138] MoldormCaveLedgeEntrance),
            "Moldorm Cave Ledge Exit": None @Door (CaveLight 19[13] MoldormCaveLedgeExit),

            "Lost Woods Pillar Crack": None @Crack(1[227] LostWoodsPillar),
            "Rosso's House Crack": None @Crack(IndoorLight 10[19] RossosHouse),

            "Fortune-Teller": HintGlasses @Event(IndoorLight/FieldLight_11_FortuneGirl[4]),
            "Hyrule Hotfoot 75s": RupeeSilver @Event(FieldLight_HyruleRace[0x21]),
            "Hyrule Hotfoot 65s": HeartPiece @Event(FieldLight_HyruleRace[0x14]),
            "Lost Woods Alcove": HeartPiece @Heart(1[46]),
            "Lost Woods Chest": RupeeR @Chest(1[133]),
            "Master Sword Pedestal": ItemSwordLv2 @Chest(34[71]),
            "Rosso Cave": RupeeR @Chest(CaveLight 6[6]),
            "Rosso (1)": PowerGlove @Event(IndoorLight/FieldLight_02_KikoriMan[0]),
            "Rosso (2)": RupeePurple @Chest(IndoorLight 10[25]),
            "[Mai] Rosso Wall": Maiamai @Maiamai(2[98]),
            "[Mai] Lost Woods Path Rock": Maiamai @Maiamai(8[29]),
            "[Mai] Lost Woods Bush": Maiamai @Maiamai(1[239]),
            "[Mai] Lost Woods Rock": Maiamai @Maiamai(1[47]),
            "[Mai] Fortune-Teller Tent": Maiamai @Maiamai(9[90]),
            "[Mai] Moldorm Ledge": Maiamai @Maiamai(6[132]),
            "[Mai] Small Pond": Maiamai @Maiamai(10[62]),
            "[Mai] Lost Woods Tree": Maiamai @Maiamai(1[229]),
        ],
    },
}
